'When
CCI-Tools/cate-desktop pull request #63
Opened 2018-10-12 08:56 UTC by dzelge

2018-10-12 09:11 UTC, hans-permana approved these changes
Looks good!

2018-11-01 10:42 UTC, forman requested changes
Please also document issue resolution in `CHANGES.txt`.

2018-11-01 10:42 UTC, forman commented on src/renderer/containers/StylesPanel.tsx
> +        if(isNaN(min) || isNaN(max)){
Add space between `if`and `(`.

2018-11-01 10:43 UTC, forman commented
Finally close issue https://github.com/CCI-Tools/cate/issues/797

2018-11-01 11:54 UTC, merged